version: "2.4"

services:
        database:
                image: mysql:8.0.33 
                restart: always
                volumes:
                        - mysql_data:/var/lib/mysql
                ports:
                        - "3306:3306"
                environment:
                        MYSQL_ROOT_PASSWORD: 'root'
                healthcheck:
                        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
                        timeout: 20s
                        retries: 10
        backend:
                build:
                        context: .
                        dockerfile: Dockerfile
                entrypoint: ["java", "-jar", "/app.jar"]
                ports:
                        - "8080:8080"
                depends_on:
                        database:
                                condition: service_healthy
volumes:
        mysql_data:
